/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from './Counter.sol/index.js';
export type { counterSol };
import type * as gameCharacterCollectionErc1155Sol from './GameCharacterCollectionERC1155.sol/index.js';
export type { gameCharacterCollectionErc1155Sol };
import type * as multiSigWalletSol from './MultiSigWallet.sol/index.js';
export type { multiSigWalletSol };
import type * as myTokenV1Sol from './MyTokenV1.sol/index.js';
export type { myTokenV1Sol };
import type * as myTokenV2Sol from './MyTokenV2.sol/index.js';
export type { myTokenV2Sol };
import type * as proxyContractSol from './ProxyContract.sol/index.js';
export type { proxyContractSol };
import type * as soulboundVisitCardErc721Sol from './SoulboundVisitCardERC721.sol/index.js';
export type { soulboundVisitCardErc721Sol };
import type * as testTokenSol from './TestToken.sol/index.js';
export type { testTokenSol };
export * as factories from './factories/index.js';
export type { Counter } from './Counter.sol/Counter.js';
export { Counter__factory } from './factories/Counter.sol/Counter__factory.js';
export type { GameCharacterCollectionERC1155 } from './GameCharacterCollectionERC1155.sol/GameCharacterCollectionERC1155.js';
export { GameCharacterCollectionERC1155__factory } from './factories/GameCharacterCollectionERC1155.sol/GameCharacterCollectionERC1155__factory.js';
export type { MultiSigWallet } from './MultiSigWallet.sol/MultiSigWallet.js';
export { MultiSigWallet__factory } from './factories/MultiSigWallet.sol/MultiSigWallet__factory.js';
export type { MyTokenV1 } from './MyTokenV1.sol/MyTokenV1.js';
export { MyTokenV1__factory } from './factories/MyTokenV1.sol/MyTokenV1__factory.js';
export type { MyTokenV2 } from './MyTokenV2.sol/MyTokenV2.js';
export { MyTokenV2__factory } from './factories/MyTokenV2.sol/MyTokenV2__factory.js';
export type { MyTokenProxy } from './ProxyContract.sol/MyTokenProxy.js';
export { MyTokenProxy__factory } from './factories/ProxyContract.sol/MyTokenProxy__factory.js';
export type { SoulboundVisitCardERC721 } from './SoulboundVisitCardERC721.sol/SoulboundVisitCardERC721.js';
export { SoulboundVisitCardERC721__factory } from './factories/SoulboundVisitCardERC721.sol/SoulboundVisitCardERC721__factory.js';
export type { TestToken } from './TestToken.sol/TestToken.js';
export { TestToken__factory } from './factories/TestToken.sol/TestToken__factory.js';