/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MultiSigWalletInterface extends Interface {
    getFunction(nameOrSignature: "changeRequiredConfirmations" | "confirmTransaction" | "confirmations" | "executeTransaction" | "getBalance" | "getOwnersCount" | "getTransaction" | "getTransactionCount" | "isConfirmed" | "isOwner" | "owners" | "requiredConfirmations" | "revokeConfirmation" | "submitTransaction" | "transactions"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposit" | "OwnerAdded" | "RequiredConfirmationsChanged" | "TransactionConfirmed" | "TransactionExecuted" | "TransactionRevoked" | "TransactionSubmitted"): EventFragment;

    encodeFunctionData(functionFragment: 'changeRequiredConfirmations', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmTransaction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmations', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'executeTransaction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOwnersCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTransaction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTransactionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'isConfirmed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owners', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'requiredConfirmations', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeConfirmation', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submitTransaction', values: [AddressLike, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'transactions', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'changeRequiredConfirmations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwnersCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTransactionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isConfirmed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requiredConfirmations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeConfirmation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitTransaction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transactions', data: BytesLike): Result;
  }

  
    export namespace DepositEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerAddedEvent {
      export type InputTuple = [owner: AddressLike];
      export type OutputTuple = [owner: string];
      export interface OutputObject {owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequiredConfirmationsChangedEvent {
      export type InputTuple = [oldRequired: BigNumberish, newRequired: BigNumberish];
      export type OutputTuple = [oldRequired: bigint, newRequired: bigint];
      export interface OutputObject {oldRequired: bigint, newRequired: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransactionConfirmedEvent {
      export type InputTuple = [transactionId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [transactionId: bigint, owner: string];
      export interface OutputObject {transactionId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransactionExecutedEvent {
      export type InputTuple = [transactionId: BigNumberish];
      export type OutputTuple = [transactionId: bigint];
      export interface OutputObject {transactionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransactionRevokedEvent {
      export type InputTuple = [transactionId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [transactionId: bigint, owner: string];
      export interface OutputObject {transactionId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransactionSubmittedEvent {
      export type InputTuple = [transactionId: BigNumberish, to: AddressLike, value: BigNumberish, data: BytesLike];
      export type OutputTuple = [transactionId: bigint, to: string, value: bigint, data: string];
      export interface OutputObject {transactionId: bigint, to: string, value: bigint, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MultiSigWallet extends BaseContract {
    
    connect(runner?: ContractRunner | null): MultiSigWallet;
    waitForDeployment(): Promise<this>;

    interface: MultiSigWalletInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    changeRequiredConfirmations: TypedContractMethod<
      [_newRequiredConfirmations: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmTransaction: TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmations: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    executeTransaction: TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getOwnersCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTransaction: TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, confirmationsCount: bigint }],
      'view'
    >
    

    
    getTransactionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isConfirmed: TypedContractMethod<
      [_transactionId: BigNumberish, _owner: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isOwner: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owners: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    requiredConfirmations: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    revokeConfirmation: TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submitTransaction: TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _data: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    transactions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, confirmationsCount: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'changeRequiredConfirmations'): TypedContractMethod<
      [_newRequiredConfirmations: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmTransaction'): TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmations'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'executeTransaction'): TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getOwnersCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTransaction'): TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, confirmationsCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTransactionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isConfirmed'): TypedContractMethod<
      [_transactionId: BigNumberish, _owner: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isOwner'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requiredConfirmations'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'revokeConfirmation'): TypedContractMethod<
      [_transactionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitTransaction'): TypedContractMethod<
      [_to: AddressLike, _value: BigNumberish, _data: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transactions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, boolean, bigint] & {to: string, value: bigint, data: string, executed: boolean, confirmationsCount: bigint }],
      'view'
    >;

    getEvent(key: 'Deposit'): TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
getEvent(key: 'OwnerAdded'): TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
getEvent(key: 'RequiredConfirmationsChanged'): TypedContractEvent<RequiredConfirmationsChangedEvent.InputTuple, RequiredConfirmationsChangedEvent.OutputTuple, RequiredConfirmationsChangedEvent.OutputObject>;
getEvent(key: 'TransactionConfirmed'): TypedContractEvent<TransactionConfirmedEvent.InputTuple, TransactionConfirmedEvent.OutputTuple, TransactionConfirmedEvent.OutputObject>;
getEvent(key: 'TransactionExecuted'): TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
getEvent(key: 'TransactionRevoked'): TypedContractEvent<TransactionRevokedEvent.InputTuple, TransactionRevokedEvent.OutputTuple, TransactionRevokedEvent.OutputObject>;
getEvent(key: 'TransactionSubmitted'): TypedContractEvent<TransactionSubmittedEvent.InputTuple, TransactionSubmittedEvent.OutputTuple, TransactionSubmittedEvent.OutputObject>;

    filters: {
      
      'Deposit(address,uint256)': TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
      Deposit: TypedContractEvent<DepositEvent.InputTuple, DepositEvent.OutputTuple, DepositEvent.OutputObject>;
    

      'OwnerAdded(address)': TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
      OwnerAdded: TypedContractEvent<OwnerAddedEvent.InputTuple, OwnerAddedEvent.OutputTuple, OwnerAddedEvent.OutputObject>;
    

      'RequiredConfirmationsChanged(uint256,uint256)': TypedContractEvent<RequiredConfirmationsChangedEvent.InputTuple, RequiredConfirmationsChangedEvent.OutputTuple, RequiredConfirmationsChangedEvent.OutputObject>;
      RequiredConfirmationsChanged: TypedContractEvent<RequiredConfirmationsChangedEvent.InputTuple, RequiredConfirmationsChangedEvent.OutputTuple, RequiredConfirmationsChangedEvent.OutputObject>;
    

      'TransactionConfirmed(uint256,address)': TypedContractEvent<TransactionConfirmedEvent.InputTuple, TransactionConfirmedEvent.OutputTuple, TransactionConfirmedEvent.OutputObject>;
      TransactionConfirmed: TypedContractEvent<TransactionConfirmedEvent.InputTuple, TransactionConfirmedEvent.OutputTuple, TransactionConfirmedEvent.OutputObject>;
    

      'TransactionExecuted(uint256)': TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
      TransactionExecuted: TypedContractEvent<TransactionExecutedEvent.InputTuple, TransactionExecutedEvent.OutputTuple, TransactionExecutedEvent.OutputObject>;
    

      'TransactionRevoked(uint256,address)': TypedContractEvent<TransactionRevokedEvent.InputTuple, TransactionRevokedEvent.OutputTuple, TransactionRevokedEvent.OutputObject>;
      TransactionRevoked: TypedContractEvent<TransactionRevokedEvent.InputTuple, TransactionRevokedEvent.OutputTuple, TransactionRevokedEvent.OutputObject>;
    

      'TransactionSubmitted(uint256,address,uint256,bytes)': TypedContractEvent<TransactionSubmittedEvent.InputTuple, TransactionSubmittedEvent.OutputTuple, TransactionSubmittedEvent.OutputObject>;
      TransactionSubmitted: TypedContractEvent<TransactionSubmittedEvent.InputTuple, TransactionSubmittedEvent.OutputTuple, TransactionSubmittedEvent.OutputObject>;
    
    };
  }