/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace GameCharacterCollectionERC1155 {
      
    export type CharacterAttributesStruct = {color: string, speed: BigNumberish, strength: BigNumberish, rarity: string}

    export type CharacterAttributesStructOutput = [color: string, speed: bigint, strength: bigint, rarity: string] & {color: string, speed: bigint, strength: bigint, rarity: string }
  
    }

  export interface GameCharacterCollectionERC1155Interface extends Interface {
    getFunction(nameOrSignature: "MAX_TOKEN_ID" | "balanceOf" | "balanceOfBatch" | "baseURI" | "characterAttributes" | "getCharacterAttributes" | "isApprovedForAll" | "mint" | "mintBatch" | "owner" | "renounceOwnership" | "safeBatchTransferFrom" | "safeTransferFrom" | "setApprovalForAll" | "setTokenURI" | "setTokenURIBatch" | "setURI" | "supportsInterface" | "transferOwnership" | "uri"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ApprovalForAll" | "BaseURIUpdated" | "CharacterAttributesSet" | "OwnershipTransferred" | "TokenURIUpdated" | "TransferBatch" | "TransferSingle" | "URI"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_TOKEN_ID', values?: undefined): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOfBatch', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'baseURI', values?: undefined): string;
encodeFunctionData(functionFragment: 'characterAttributes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCharacterAttributes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isApprovedForAll', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'mintBatch', values: [AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'safeBatchTransferFrom', values: [AddressLike, AddressLike, BigNumberish[], BigNumberish[], BytesLike]): string;
encodeFunctionData(functionFragment: 'safeTransferFrom', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setTokenURI', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'setTokenURIBatch', values: [BigNumberish[], string[]]): string;
encodeFunctionData(functionFragment: 'setURI', values: [string]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'uri', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MAX_TOKEN_ID', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOfBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'baseURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'characterAttributes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCharacterAttributes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeBatchTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'safeTransferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenURIBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uri', data: BytesLike): Result;
  }

  
    export namespace ApprovalForAllEvent {
      export type InputTuple = [account: AddressLike, operator: AddressLike, approved: boolean];
      export type OutputTuple = [account: string, operator: string, approved: boolean];
      export interface OutputObject {account: string, operator: string, approved: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BaseURIUpdatedEvent {
      export type InputTuple = [newBaseURI: string];
      export type OutputTuple = [newBaseURI: string];
      export interface OutputObject {newBaseURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CharacterAttributesSetEvent {
      export type InputTuple = [tokenId: BigNumberish, color: string, speed: BigNumberish, strength: BigNumberish, rarity: string];
      export type OutputTuple = [tokenId: bigint, color: string, speed: bigint, strength: bigint, rarity: string];
      export interface OutputObject {tokenId: bigint, color: string, speed: bigint, strength: bigint, rarity: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenURIUpdatedEvent {
      export type InputTuple = [tokenId: BigNumberish, tokenURI: string];
      export type OutputTuple = [tokenId: bigint, tokenURI: string];
      export interface OutputObject {tokenId: bigint, tokenURI: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferBatchEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[]];
      export type OutputTuple = [operator: string, from: string, to: string, ids: bigint[], values: bigint[]];
      export interface OutputObject {operator: string, from: string, to: string, ids: bigint[], values: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferSingleEvent {
      export type InputTuple = [operator: AddressLike, from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish];
      export type OutputTuple = [operator: string, from: string, to: string, id: bigint, value: bigint];
      export interface OutputObject {operator: string, from: string, to: string, id: bigint, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace URIEvent {
      export type InputTuple = [value: string, id: BigNumberish];
      export type OutputTuple = [value: string, id: bigint];
      export interface OutputObject {value: string, id: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GameCharacterCollectionERC1155 extends BaseContract {
    
    connect(runner?: ContractRunner | null): GameCharacterCollectionERC1155;
    waitForDeployment(): Promise<this>;

    interface: GameCharacterCollectionERC1155Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_TOKEN_ID: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOfBatch: TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >
    

    
    baseURI: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    characterAttributes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, string] & {color: string, speed: bigint, strength: bigint, rarity: string }],
      'view'
    >
    

    
    getCharacterAttributes: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [GameCharacterCollectionERC1155.CharacterAttributesStructOutput],
      'view'
    >
    

    
    isApprovedForAll: TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    mintBatch: TypedContractMethod<
      [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    safeBatchTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    safeTransferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setTokenURI: TypedContractMethod<
      [tokenId: BigNumberish, tokenURI_: string, ],
      [void],
      'nonpayable'
    >
    

    
    setTokenURIBatch: TypedContractMethod<
      [tokenIds: BigNumberish[], tokenURIs: string[], ],
      [void],
      'nonpayable'
    >
    

    
    setURI: TypedContractMethod<
      [newBaseURI: string, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    uri: TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_TOKEN_ID'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, id: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOfBatch'): TypedContractMethod<
      [accounts: AddressLike[], ids: BigNumberish[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'baseURI'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'characterAttributes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, string] & {color: string, speed: bigint, strength: bigint, rarity: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getCharacterAttributes'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [GameCharacterCollectionERC1155.CharacterAttributesStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedForAll'): TypedContractMethod<
      [account: AddressLike, operator: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, id: BigNumberish, amount: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintBatch'): TypedContractMethod<
      [to: AddressLike, ids: BigNumberish[], amounts: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeBatchTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ids: BigNumberish[], values: BigNumberish[], data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'safeTransferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, id: BigNumberish, value: BigNumberish, data: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [operator: AddressLike, approved: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, tokenURI_: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenURIBatch'): TypedContractMethod<
      [tokenIds: BigNumberish[], tokenURIs: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setURI'): TypedContractMethod<
      [newBaseURI: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uri'): TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >;

    getEvent(key: 'ApprovalForAll'): TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
getEvent(key: 'BaseURIUpdated'): TypedContractEvent<BaseURIUpdatedEvent.InputTuple, BaseURIUpdatedEvent.OutputTuple, BaseURIUpdatedEvent.OutputObject>;
getEvent(key: 'CharacterAttributesSet'): TypedContractEvent<CharacterAttributesSetEvent.InputTuple, CharacterAttributesSetEvent.OutputTuple, CharacterAttributesSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokenURIUpdated'): TypedContractEvent<TokenURIUpdatedEvent.InputTuple, TokenURIUpdatedEvent.OutputTuple, TokenURIUpdatedEvent.OutputObject>;
getEvent(key: 'TransferBatch'): TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
getEvent(key: 'TransferSingle'): TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
getEvent(key: 'URI'): TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;

    filters: {
      
      'ApprovalForAll(address,address,bool)': TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
      ApprovalForAll: TypedContractEvent<ApprovalForAllEvent.InputTuple, ApprovalForAllEvent.OutputTuple, ApprovalForAllEvent.OutputObject>;
    

      'BaseURIUpdated(string)': TypedContractEvent<BaseURIUpdatedEvent.InputTuple, BaseURIUpdatedEvent.OutputTuple, BaseURIUpdatedEvent.OutputObject>;
      BaseURIUpdated: TypedContractEvent<BaseURIUpdatedEvent.InputTuple, BaseURIUpdatedEvent.OutputTuple, BaseURIUpdatedEvent.OutputObject>;
    

      'CharacterAttributesSet(uint256,string,uint256,uint256,string)': TypedContractEvent<CharacterAttributesSetEvent.InputTuple, CharacterAttributesSetEvent.OutputTuple, CharacterAttributesSetEvent.OutputObject>;
      CharacterAttributesSet: TypedContractEvent<CharacterAttributesSetEvent.InputTuple, CharacterAttributesSetEvent.OutputTuple, CharacterAttributesSetEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokenURIUpdated(uint256,string)': TypedContractEvent<TokenURIUpdatedEvent.InputTuple, TokenURIUpdatedEvent.OutputTuple, TokenURIUpdatedEvent.OutputObject>;
      TokenURIUpdated: TypedContractEvent<TokenURIUpdatedEvent.InputTuple, TokenURIUpdatedEvent.OutputTuple, TokenURIUpdatedEvent.OutputObject>;
    

      'TransferBatch(address,address,address,uint256[],uint256[])': TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
      TransferBatch: TypedContractEvent<TransferBatchEvent.InputTuple, TransferBatchEvent.OutputTuple, TransferBatchEvent.OutputObject>;
    

      'TransferSingle(address,address,address,uint256,uint256)': TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
      TransferSingle: TypedContractEvent<TransferSingleEvent.InputTuple, TransferSingleEvent.OutputTuple, TransferSingleEvent.OutputObject>;
    

      'URI(string,uint256)': TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
      URI: TypedContractEvent<URIEvent.InputTuple, URIEvent.OutputTuple, URIEvent.OutputObject>;
    
    };
  }